### PR TITLE
Better swift support

### PR DESCRIPTION
**Pull request by Sega-Zero**
Applied nullabitily macros and light generics as mentioned in #106 
Also, `FICImageTable` class has been modernized a little bit:
- declared `init` and `new` methods as unavailable in favor of `initWithFormat:imageCache:`
- added [`NS_DESIGNATED_INITIALIZER`](https://developer.apple.com/library/ios/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html#//apple_ref/doc/uid/TP40014150-CH1-SW8) for `initWithFormat:imageCache:`

It is much better than a crash in runtime.

### CODE REVIEW

**Comment by mallorypaine** [comment]
@Sega-Zero my apologies at the delay in looking at this. any chance you can address the conflicts here?

**Comment by Sega-Zero** [comment]
sure, fixed

**Comment by mallorypaine** [comment]
Thanks for the quick response. Do you think we need any other changes for Swift 2.3? Any thoughts about support for Swift 3?

**Comment by Sega-Zero** [comment]
As long as FastImageCache is used as a framework - nothing more special to be added to support newer swift versions, I think. Nullability and light generics is a must to work comfortable in swift. Haven't looked at 3.0 yet, 2.3 most certainly stay the same.

I'll check if there should be more changes for swift 3 and make a new PR if any.

**Pull request merged**
