### PR TITLE
Fixes some issues around Xcode 9 yelling about using UIKit on background threads

### PR DESCRIPTION
**Pull request by rhaining**
In Xcode 9, the new main thread checker kept warning me about FastImageCache using UIApplication's isProtectedDataAvailable on a background thread. This should be innocuous, but I think Xcode 9 is just broadly looking at UIKit on background threads.

More consequently, this was preventing me from running unit tests locally on my own project.

The basic change here is to use NSNotificationCenter to watch for notifications when protected data becomes available or unavailable, and maintain that state as a static variable, which the instances can then utilize.

### CODE REVIEW

**Comment by rhaining** [comment]
This also resolves this issue: https://github.com/path/FastImageCache/issues/150

**Comment by RodBrown1988** [comment]
@rhaining After chatting with @mallorypaine on Twitter, he has left Path, and this repo no longer has anyone with write access actively working on it.

I'm looking at upgrading my personal version of it, and perhaps starting a canonical side fork now that Path seem to have abandoned this repo.

**Comment by rhaining** [comment]
@RodBrown1988 dang! thanks for the heads-up.

**Comment by yoon-boom** [comment]
I guess can't find podspec, no maintenance (looks like they left **path**) only option is either fork-> create own branch then create your own podspec or manually hardcopy files is the only option.

**Comment by mallorypaine** [comment]
Please open PRs against my fork here: https://github.com/mallorypaine/FastImageCache

I will continue to maintain FIC even though Path itself is no longer maintaining it.

**Comment by Sega-Zero** [comment]
@rhaining, will you do this? I can make a PR if you don't have free time for it

**Comment by rhaining** [comment]
@Sega-Zero this PR is ready to be merged

**Comment by Sega-Zero** [comment]
@rhaining please, read the thread, @mallorypaine cannot merge it in this repo, we need a PR into a fork

**Comment by Sega-Zero** [comment]
@mallorypaine is it possible to [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) this repo to you? Is there anyone in Path who can do it?

**Comment by mallorypaine** [comment]
No idea. I don’t think there’s a single person left from when I was there.

**Comment by k-krzyszczak** [comment]
@rhaining ETA of new version with this merge?

**Comment by Sega-Zero** [comment]
@JeaDay this has been merged in https://github.com/mallorypaine/FastImageCache/pull/1

@mallorypaine Is it possible to update the pod? Or maybe create a new one?

**Comment by rhaining** [comment]
@JeaDay i don't work for Path or know anyone there. as far as i know, this project is unmaintained now. i have a fork over here https://github.com/rhaining/FastImageCache/ with those changes.

**Pull request closed without merging**
