### PR TITLE
Use NSJSONSerialization instead of NSPropertyListSerialization for better performance

### PR DESCRIPTION
**Pull request by donholly**
Use NSJSONSerialization instead of NSPropertyListSerialization to improve the speed serializing Image Table metadata before writing to disk. This change is backward compatible with previous Image Tables

### CODE REVIEW

**Comment by mallorypaine** [comment]
@donholly my apologies for letting this PR languish for so long. Did you take any measurements here to understand exactly what sorts of performance gains are achieved?

**Comment by donholly** [comment]
I did a long time ago. They were definitely noticeable. I can probably benchmark it again - I'm actually digging around pretty deep right now in my fork (more below).

I also was able to squeeze a little more performance out of saving the metadata by making sure the queue to do so wasn't getting backed up with too many incremental writes by doing this:

https://github.com/donholly/FastImageCache/commit/d9072317a270e549076ed42b752b0159c2ba5365

I actually just spent the last couple days adding support for dynamic image formats with FIC. The idea was to not have to worry about what sizes the app would be responsible for caching (and allow you to provide new FICImageFormats as required).

I suppose this is a step in the direction of allowing the storage of any aspect ratio image with FIC. 

You can take a look at my progress with that here:
https://github.com/donholly/FastImageCache/commits/on_the_fly_formats

I'm not sure how clean it will end up being as a pull request, so I may keep it branched for now unless you'd like to take a look.

Thanks again for providing such an awesome open source project! The performance gains and memory savings I'm seeing with FIC is incredible :+1:

**Comment by donholly** [comment]
I realize now that first link I sent with regards to speeding up `saveMetadata` may be a little confusing since it was my revert from using NSOutputStream back to in-memory JSON serialization. I found that NSOutputStream was quite a bit slower (albeit used less memory) than serializing in memory and saving to disk.

I was seeing very large memory spikes when scrolling fast through many photos that were getting cached as they loaded. What I did was prevent incremental saves from occurring if another was queued up to overwrite all the same data.

Now instead of:

processImage:        |    1   |    2    |    3    |    4    |
saveMetadata         | save | save | save | save | 

It's more like:

processImage:        |    1   |    2    |    3    |    4    |
saveMetadata         | save | skip  |  skip  | save | 

Once those imageTables get pretty large, the serialization process gets pretty expensive. Limiting the number of times serialization occurs seems to help quite a bit.

I may investigate a way to get incremental saves, though that seems like quite a challenge given the MRU cache, etc.

**Comment by mallorypaine** [comment]
@donholly I'm going to try to take a look at this stuff. Totally agree re: serialization cost with big tables. Would love to chat about the on-the-fly-formats...I've wanted this feature myself for a long time.

**Comment by donholly** [comment]
My fork (branch: on_the_fly_formats) has this working now. Might need to do some cleanup work, but overall it's working for me!

**Comment by LucasTizma** [comment]
Very cool stuff! Much-needed improvements to FIC. :)

**Comment by mallorypaine** [comment]
@donholly I'd like to land your improvements, for reals this time. :-) However, looking at this commit list and at what you wrote, it sounds like we don't want the NSOutputStream changes if I'm reading this right. Any chance you could resubmit this PR with just the commits you'd like to land? I'm going to try to spend some time this week on cleaning up FIC and hopefully releasing a new version sometime this month. Would love to take a look at the on-the-fly formats as well. Did you end up using your OTF in shipping software? If you're happy with it, could you submit a separate PR with those changes?

**Comment by donholly** [comment]
Hi @mallorypaine,

Sounds good!

The PLIST to NSJSONSerialization commit is here:
https://github.com/donholly/FastImageCache/commit/9bdc50d0ccea675ae779a75668288b404adfbe41

I can look to pull that into a new PR for you.

I found that the NSOutputStream changes I made were actually a performance degradation (took longer to save the metadata vs NSJSONSerialization). I would like to figure out a better way to save the .metadata files in the future. As they grow (and become potentially > 1 or 2 MB), the frequent saves they endure can cause some significant memory and CPU spikes. 

Some of this was caused by saving the metadata so frequently. This patch made a noticeable difference for me.:
https://github.com/donholly/FastImageCache/commit/d9072317a270e549076ed42b752b0159c2ba5365

As I detailed in an above comment, it prevents many saves from occurring back-to-back-to-back. Instead, if 6 saves are requested in a row (while a save is taking place), only that save and one additional save that was queued up will happen.

As for the on-the-fly formats: they're working well for me! I have shipped a version of the app to the App Store using that branch and haven't had any notable issues (other than some user complaints about the amount of disk space we use sometimes now)... hard to get a win-win when performance demands uncompressed images are stored on disk :)

This project was a part of an overhaul to our app's internal image retrieval and caching layer. I built it from scratch with a dependency on FIC (Thanks!). I ended up building most of the core functionality for on-the-fly formats into my abstraction layer. As of right now, that's in a private repo on GitHub. I'm happy to share how I got on-the-fly formats working with you, though I don't think it will be straight forward to get all of the changes into FIC for a PR very quickly.

This is the vast majority of my abstraction layer (along with the FICEntity extension):
https://gist.github.com/donholly/934f52eacf510943a110

I essentially just subclassed `FICImageFormat` and `FICImageCache`. It should be easy to get most of that baked directly into FIC. The API isn't as pretty as you might want it to be for a public release. I wanted to make sure it would do what I wanted before I went through the effort.

Let me know if you have any questions. I can also add to you our private repo if you want to take a deeper look into what I did.

**Comment by mallorypaine** [comment]
@donholly looking at your version check, the idea is sound but i think there may be issues with that implementation. basically, you're using a global version for all tables. table A's metadata could failed to be written if table B initiates a save. i'll fix this by using one version per table.

**Comment by donholly** [comment]
@mallorypaine that's a good point :+1: 

Couldn't that be fixed by simply making the `__metadataVersion` non-static? (is that what you meant by version per table?)

**Comment by mallorypaine** [comment]
OK, I landed NSJSON + skipping old versions. Closing this. Progress!

**Pull request closed without merging**
