### PR TITLE
Add method to get total impact of disk usage

### PR DESCRIPTION
**Pull request by rromanchuk**
Some developers like to give the user the ability to reset their cache. Add a convenience method for developers to fetch the disk usage by `FastImageCache` 

Related: #65

### CODE REVIEW

**Comment by mallorypaine** [comment]
Apologies for the delay in handling PRs. I'm going to spend some time this week and next to maintain FIC and I plan to put together a new release this month. 

One question: why are there two basically identical implementations of the same byte counting method?

**Comment by rromanchuk** [comment]
In an uber right now and forgot this PR, but I think it's totally invalid
if I remember correctly. Total disk space is assigned during configuration
so the implementor should already know this value. I was probably thinking
of FIC as a file cache similar to sdwebimage, which it's not. Probably just
forgot to close this PR

**Comment by rromanchuk** [comment]
From what I remember the "file" per format is allocated from initialization, so there is no concept of growing cache, and because of this, clearing the cache doesn't make any sense in the first place

**Comment by mallorypaine** [comment]
The files aren't allocated initially. They grow from zero up to max entry size as entries are added.

**Pull request closed without merging**
