### PR TITLE
Carthage + Single Project ( Demo + Lib)

### PR DESCRIPTION
**Pull request by RuiAAPeres**

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Please, let me know your thoughts on the exposed headers:

```
#import <FastImageCache/FICImageCache.h>
#import <FastImageCache/FICEntity.h> 
```

**Comment by Rupert-RR** [comment]
This would be nice!

**Comment by dmcrodrigues** [comment]
Yeah, this would be really handy!

**Comment by Krisiacik** [comment]
We need this please :) !

**Pull request merged**
